name: Build Sample

# on: [push, pull_request]
on:
  push:
    branches:
      - rel
    tags:
      - test

jobs:
    build-win:
        name: Build for Windows
        runs-on: windows-latest
        strategy:
          fail-fast: false
          matrix:
              # arch: [x64, ARM64]
              arch: [x64]
              target: [Windows]
        steps:
          - uses: actions/checkout@v4
            with:
                submodules: recursive
          - name: Configure
            run: cmake -DCMAKE_SYSTEM_NAME=${{ matrix.target }} -DCMAKE_SYSTEM_VERSION="10.0" -A${{ matrix.arch }} -S . -B build
          - name: Build
            run: cmake --build build --target sdl-min --config Release
          - name: Upload Build
            uses: actions/upload-artifact@v4
            if: ${{ matrix.target != 'WindowsStore' }}
            with:
                name: sdl-min-${{ matrix.target }}-${{ matrix.arch }}
                path: |
                    build/Release/*.exe
                    build/Release/*.dll
                    build/Release/*.ttf
                    build/Release/*.ogg
                    build/Release/*.svg
